### ISSUE TITLE
Sample data 

### ISSUE THREAD

**Issue by geointerest** [davemfish/ttapp#18]
Suggest including a link on the main page that allows user to download a sample run.  This way the don't need InVEST to explore the tool.  Also, IE didn't work for me.  Might want to mention compatible browsers.

**Comment by davemfish** [comment]
Two Options:

1) As Gregg suggests, we could provide a link that downloads a sample InVEST output workspace. Then the user can use the app normally by uploading the required files from that workspace. 

2) Alternatively we include a 'Demo' button that loads data from our servers directly into the app, skipping the downloading and re-uploading step. 
PRO: This makes it easier for the user to quickly try out the app and it gets pretty content on the screen right away. 
CON: by skipping the upload step it does less towards teaching the user exactly how to use the app with their own results. Also this requires slightly more programming than the first option.

**Comment by davemfish** [comment]
Need to solve issue #22 before this one, so that people can load the demo/sample data and then load their own immediately after.

**Comment by davemfish** [comment]
Set up sample data in rec-dash.php which has the newest php session stuff, and then bring all changes to cv-dash.php

Basically need a button that sets the php var $pathid (or the JS var sessPath) to a static sample directory that has outputs of the R script.

**Comment by davemfish** [comment]
committed 1/14/2015 before 1:24pm
