### ISSUE TITLE
Can't locate coastal_exposure.csv after default data run

### ISSUE THREAD

**Issue by dcdenu4** [davemfish/ttapp#31]
I run coastal vulnerability with default data and navigate to workspace/output/coastal_exposure/ . I expect to find coastal_exposure.csv, but only find .tif files.

Could it be that I didn't select a certain option in the input selection for the model?

**Comment by davemfish** [comment]
You did everything right except using 3.1.0. Due to a bug in the 3.1.0 release the csv files were not generated by the model. Nic has fixed this as of last week, so you could try a recent dev build or 3.0.1.

This info is in the About tab of the app, but maybe I should post it on the forum as well.
