### ISSUE TITLE
hra big popups move the map view 

### ISSUE THREAD

**Issue by woodsp** [davemfish/ttapp#45]
In cells with many habitats and/or stressors, the popup can exceed the size of the map view (example below).  The unfortunate consequence of this is that the map viewer then jumps to the top of the popup box and the user loses their position on the map.   Trimming some of the whitespace in the popup might help, but doesn't solve the issue.  Can you have the map hold it's place, cutting-off the top of the popup instead of the bottom?  Or some other solution?

![bigolepopup](https://cloud.githubusercontent.com/assets/2513700/7541646/bb913806-f56b-11e4-8f93-59607963d634.jpg)

**Comment by davemfish** [comment]
How about moving the popup content to a table off the map entirely? Cleaning up the whitespace is a good idea too.
![outside-the-map-popup](https://cloud.githubusercontent.com/assets/4071255/7541896/866cb0a4-f56d-11e4-97ad-7566d604d581.png)
